# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = quick_client
DESTDIR = ../out/
CONFIG += debug
QT += widgets core gui
LIBS += -L../out/lib \
    -lquick
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(quick_client.pri)
