# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./quick_server.h
SOURCES += ./quick_server.cpp \
    ./main.cpp
FORMS += ./quick_server.ui
RESOURCES += quick_server.qrc
